export enum ReservationState {
  PENDING = 'PENDING',              
  ACCEPTED = 'ACCEPTED',
  CAPTURE_PENDING = 'CAPTURE_PENDING',
  CANCEL_PENDING = 'CANCEL_PENDING',  
  SOLD = 'SOLD',  
  EXPIRED_BY_SHOPPER = 'EXPIRED_BY_SHOPPER',
  EXPIRED_BY_SELLER = 'EXPIRED_BY_SELLER',
  CANCELLED_BY_SHOPPER = 'CANCELLED_BY_SHOPPER',
  CANCELLED_BY_SELLER = 'CANCELLED_BY_SELLER', 
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED'
}